name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Dependencies
        run: |
          npm install @semantic-release/commit-analyzer@10.0.4 \
                      @semantic-release/release-notes-generator@11.0.7 \
                      @semantic-release/github@9.0.4 \
                      conventional-changelog-eslint@5.0.0 \
                      semantic-release@21.1.1
      - name: Create Release
        run: |
          npx semantic-release -e ./.github/.releaserc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
